name: build-and-push-rangersinfo
on: 
  push: null
  schedule:
    - cron: '01 10 * * *'

env:
  TIDBYT_API_TOKEN: ${{ secrets.TIDBYT_API_TOKEN }}
  TIDBYT_DEVICE_ID: ${{ secrets.TIDBYT_DEVICE_ID }}
  TIDBYT_API_TOKEN_KYLE: ${{ secrets.TIDBYT_API_TOKEN_KYLE }}
  TIDBYT_DEVICE_ID_KYLE: ${{ secrets.TIDBYT_DEVICE_ID_KYLE }}
  TIDBYT_API_TOKEN_JASON: ${{ secrets.TIDBYT_API_TOKEN_JASON }}
  TIDBYT_DEVICE_ID_JASON: ${{ secrets.TIDBYT_DEVICE_ID_JASON }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-docker-rangersinfo
      - uses: ./.github/actions/run-docker-wc-chase